#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WlcDailyTrackAndroid
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class StatsHtml : StatsHtmlBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<div");

WriteLiteral(" class=\"stats-table-wrapper\"");

WriteLiteral(">\r\n<table");

WriteLiteral(" class=\"stats-table\"");

WriteLiteral(">\r\n<thead>\r\n<tr");

WriteLiteral(" class=\"day-count\"");

WriteLiteral(">\r\n<th>\r\n<span>Day</span>\r\n</th>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-03\"");

WriteLiteral(">\r\n1\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-04\"");

WriteLiteral(">\r\n2\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-05\"");

WriteLiteral(">\r\n3\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-06\"");

WriteLiteral(">\r\n4\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-07\"");

WriteLiteral(">\r\n5\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-08\"");

WriteLiteral(">\r\n6\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-09\"");

WriteLiteral(">\r\n7\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-10\"");

WriteLiteral(">\r\n8\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-11\"");

WriteLiteral(">\r\n9\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-12\"");

WriteLiteral(">\r\n10\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-13\"");

WriteLiteral(">\r\n11\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-14\"");

WriteLiteral(">\r\n12\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-15\"");

WriteLiteral(">\r\n13\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-16\"");

WriteLiteral(">\r\n14\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-17\"");

WriteLiteral(">\r\n15\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-18\"");

WriteLiteral(">\r\n16\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-19\"");

WriteLiteral(">\r\n17\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-20\"");

WriteLiteral(">\r\n18\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-21\"");

WriteLiteral(">\r\n19\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-22\"");

WriteLiteral(">\r\n20\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-23\"");

WriteLiteral(">\r\n21\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-24\"");

WriteLiteral(">\r\n22\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-25\"");

WriteLiteral(">\r\n23\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-26\"");

WriteLiteral(">\r\n24\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-27\"");

WriteLiteral(">\r\n25\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-28\"");

WriteLiteral(">\r\n26\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-29\"");

WriteLiteral(">\r\n27\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-30\"");

WriteLiteral(">\r\n28\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-05-31\"");

WriteLiteral(">\r\n29\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-01\"");

WriteLiteral(">\r\n30\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-02\"");

WriteLiteral(">\r\n31\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-03\"");

WriteLiteral(">\r\n32\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-04\"");

WriteLiteral(">\r\n33\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-05\"");

WriteLiteral(">\r\n34\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-06\"");

WriteLiteral(">\r\n35\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-07\"");

WriteLiteral(">\r\n36\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-08\"");

WriteLiteral(">\r\n37\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-09\"");

WriteLiteral(">\r\n38\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-10\"");

WriteLiteral(">\r\n39\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-11\"");

WriteLiteral(">\r\n40\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-12\"");

WriteLiteral(">\r\n41\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-13\"");

WriteLiteral(">\r\n42\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-14\"");

WriteLiteral(">\r\n43\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-15\"");

WriteLiteral(">\r\n44\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-16\"");

WriteLiteral(">\r\n45\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-17\"");

WriteLiteral(">\r\n46\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-18\"");

WriteLiteral(">\r\n47\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-19\"");

WriteLiteral(">\r\n48\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-20\"");

WriteLiteral(">\r\n49\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-21\"");

WriteLiteral(">\r\n50\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-22\"");

WriteLiteral(">\r\n51\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-23\"");

WriteLiteral(">\r\n52\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-24\"");

WriteLiteral(">\r\n53\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-25\"");

WriteLiteral(">\r\n54\r\n</span>\r\n</td>\r\n<td>\r\n<span");

WriteLiteral(" title=\"2014-06-26\"");

WriteLiteral(">\r\n55\r\n</span>\r\n</td>\r\n</tr>\r\n</thead>\r\n<tbody>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"nutrition\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nNutrition\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-nutrition icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts3\"");

WriteLiteral(">\r\n<span>\r\n4\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n5\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts2\"");

WriteLiteral(">\r\n<span>\r\n3\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"workout\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nWorkout\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-workout icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"mobilize\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nMobilize\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-mobilize icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"supplement\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nSupplement\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-supplement icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"water\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nLifestyle\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-water icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n1\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"graphic-icon-th\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nTotal\r\n</div>\r\n<span>\r\n<div");

WriteLiteral(" class=\"icon-signal\"");

WriteLiteral(@"></div>
</span>
</th>
<td>
7
</td>
<td>
8
</td>
<td>
8
</td>
<td>
10
</td>
<td>
8
</td>
<td>
10
</td>
<td>
7
</td>
<td>
10
</td>
<td>
9
</td>
<td>
9
</td>
<td>
9
</td>
<td>
6
</td>
<td>
10
</td>
<td>
5
</td>
<td>
9
</td>
<td>
9
</td>
<td>
10
</td>
<td>
11
</td>
<td>
11
</td>
<td>
9
</td>
<td>
9
</td>
<td>
6
</td>
<td>
4
</td>
<td>
5
</td>
<td>
10
</td>
<td>
10
</td>
<td>
9
</td>
<td>
9
</td>
<td>
10
</td>
<td>
11
</td>
<td>
11
</td>
<td>
10
</td>
<td>
9
</td>
<td>
5
</td>
<td>
10
</td>
<td>
10
</td>
<td>
10
</td>
<td>
11
</td>
<td>
11
</td>
<td>
9
</td>
<td>
5
</td>
<td>
4
</td>
<td>
8
</td>
<td>
5
</td>
<td>
11
</td>
<td>
11
</td>
<td>
11
</td>
<td>

</td>
<td>
9
</td>
<td>

</td>
<td>
7
</td>
<td>
9
</td>
<td>
9
</td>
<td>

</td>
<td>

</td>
</tr>
<tr");

WriteLiteral(" class=\"spacer\"");

WriteLiteral("></tr>\r\n<tr>\r\n<th");

WriteLiteral(" class=\"bonus\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\nBonus\r\n</div>\r\n<span");

WriteLiteral(" class=\"icon-level-bonus icon-level-21\"");

WriteLiteral("></span>\r\n</th>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts4\"");

WriteLiteral(">\r\n<span>\r\n2\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n0\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n<td");

WriteLiteral(" class=\"parts0\"");

WriteLiteral(">\r\n<span>\r\n\r\n</span>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" class=\"reflections-count\"");

WriteLiteral(">\r\n<th>\r\n<div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">Reflections Written</div>\r\n</th>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"bonus-earned\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td");

WriteLiteral(" class=\"reflection-written\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon-ok\"");

WriteLiteral("></span></td>\r\n<td></td>\r\n<td></td>\r\n</tr>\r\n<tr");

WriteLiteral(" class=\"reflections-info-block\"");

WriteLiteral(">\r\n<th></th>\r\n<td");

WriteLiteral(" colspan=\"36\"");

WriteLiteral(">Entering 5 consecutive reflections earns you 2 bonus points.</td>\r\n</tr>\r\n</tbod" +
"y>\r\n</table>\r\n</div>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class StatsHtmlBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
