#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WlcDailyTrackAndroid.Resource", IsApplication=true)]

namespace WlcDailyTrackAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int points_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ab_white = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int blue_background = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int red_background = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int lifestyle_switch = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout2 = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int mobilize_switch = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int nutritionSpinner = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int pointView = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int supplement_switch = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int textView1 = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int textView3 = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int workout_switch = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CircleLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int Mono_Android_Theme_Splash = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ThemeActionBar = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int WlcTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int WlcTheme_ActionBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int WlcTheme_ActionBar_TitleTextStyle = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
